services:

  app_proxy:
    environment:
      APP_HOST: gbere-power-nut_app_1
      APP_PORT: 3493
    
  app:
    image: instantlinux/nut-upsd:2.8.3-r3
    init: true
    restart: on-failure
    privileged: true
    environment:
      API_PASSWORD: changeme
      DRIVER: nutdrv_qx
      # VENDORID: 0665

    ports:
      - "3493:3493"
    volumes:
      # - ${APP_DATA_DIR}/data/config:/etc/nut
      # - ${APP_DATA_DIR}/data/state:/var/state/nut
      - /dev:/dev
